//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSideloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QSideloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Settings.
        /// </summary>
        public static string ApplySettingsButton {
            get {
                return ResourceManager.GetString("ApplySettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Name.
        /// </summary>
        public static string AppNameHeader {
            get {
                return ResourceManager.GetString("AppNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Games.
        /// </summary>
        public static string AvailableGamesHeader {
            get {
                return ResourceManager.GetString("AvailableGamesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run backup.
        /// </summary>
        public static string BackupConfirmationButton {
            get {
                return ResourceManager.GetString("BackupConfirmationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Name.
        /// </summary>
        public static string BackupNameHeader {
            get {
                return ResourceManager.GetString("BackupNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application files (APK + OBB).
        /// </summary>
        public static string BackupPartsSelectionApplicationData {
            get {
                return ResourceManager.GetString("BackupPartsSelectionApplicationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application data (saves and settings).
        /// </summary>
        public static string BackupPartsSelectionApplicationFiles {
            get {
                return ResourceManager.GetString("BackupPartsSelectionApplicationFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select parts you want to backup:.
        /// </summary>
        public static string BackupPartsSelectionPrompt {
            get {
                return ResourceManager.GetString("BackupPartsSelectionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Selected.
        /// </summary>
        public static string BackupSelectedButton {
            get {
                return ResourceManager.GetString("BackupSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup selected games.
        /// </summary>
        public static string BackupSelectedGamesTooltip {
            get {
                return ResourceManager.GetString("BackupSelectedGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups location.
        /// </summary>
        public static string BackupsLocation {
            get {
                return ResourceManager.GetString("BackupsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery level.
        /// </summary>
        public static string BatteryLevel {
            get {
                return ResourceManager.GetString("BatteryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates automatically.
        /// </summary>
        public static string CheckUpdatesAutomatically {
            get {
                return ResourceManager.GetString("CheckUpdatesAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Now.
        /// </summary>
        public static string CheckUpdatesNowButton {
            get {
                return ResourceManager.GetString("CheckUpdatesNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        public static string ContentsHeader {
            get {
                return ResourceManager.GetString("ContentsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy installation ID.
        /// </summary>
        public static string CopyInstallationIdButton {
            get {
                return ResourceManager.GetString("CopyInstallationIdButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current device serial.
        /// </summary>
        public static string CurrentDeviceSerial {
            get {
                return ResourceManager.GetString("CurrentDeviceSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateHeader {
            get {
                return ResourceManager.GetString("DateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will delete selected backups.
        ///Are you sure you want to continue?.
        /// </summary>
        public static string DeleteBackupsConfirmation {
            get {
                return ResourceManager.GetString("DeleteBackupsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete.
        /// </summary>
        public static string DeleteBackupsConfirmationButton {
            get {
                return ResourceManager.GetString("DeleteBackupsConfirmationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected backups.
        /// </summary>
        public static string DeleteSelectedBackupsTooltip {
            get {
                return ResourceManager.GetString("DeleteSelectedBackupsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected.
        /// </summary>
        public static string DeleteSelectedButton {
            get {
                return ResourceManager.GetString("DeleteSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Info:.
        /// </summary>
        public static string DeviceInfoColon {
            get {
                return ResourceManager.GetString("DeviceInfoColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device list.
        /// </summary>
        public static string DeviceList {
            get {
                return ResourceManager.GetString("DeviceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate All.
        /// </summary>
        public static string DonateAllButton {
            get {
                return ResourceManager.GetString("DonateAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload all eligible games.
        /// </summary>
        public static string DonateAllGamesTooltip {
            get {
                return ResourceManager.GetString("DonateAllGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate Games.
        /// </summary>
        public static string DonateGamesHeader {
            get {
                return ResourceManager.GetString("DonateGamesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate Selected.
        /// </summary>
        public static string DonateSelectedButton {
            get {
                return ResourceManager.GetString("DonateSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload selected games.
        /// </summary>
        public static string DonateTooltip {
            get {
                return ResourceManager.GetString("DonateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download &amp; Install.
        /// </summary>
        public static string DownloadAndInstallButton {
            get {
                return ResourceManager.GetString("DownloadAndInstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download &amp; Install Selected.
        /// </summary>
        public static string DownloadAndInstallSelectedButton {
            get {
                return ResourceManager.GetString("DownloadAndInstallSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and install selected games.
        /// </summary>
        public static string DownloadAndInstallSelectedGamesTooltip {
            get {
                return ResourceManager.GetString("DownloadAndInstallSelectedGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download/upload bandwidth limit.
        /// </summary>
        public static string DownloaderBandwidthLimit {
            get {
                return ResourceManager.GetString("DownloaderBandwidthLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit in KiB/s, or use suffix B|K|M|G|T|P (leave empty for unlimited).
        /// </summary>
        public static string DownloaderBandwidthLimitTooltip {
            get {
                return ResourceManager.GetString("DownloaderBandwidthLimitTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Selected.
        /// </summary>
        public static string DownloadSelectedButton {
            get {
                return ResourceManager.GetString("DownloadSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download selected games.
        /// </summary>
        public static string DownloadSelectedGamesTooltip {
            get {
                return ResourceManager.GetString("DownloadSelectedGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads location.
        /// </summary>
        public static string DownloadsLocation {
            get {
                return ResourceManager.GetString("DownloadsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads pruning policy.
        /// </summary>
        public static string DownloadsPruningPolicy {
            get {
                return ResourceManager.GetString("DownloadsPruningPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable auto donation.
        /// </summary>
        public static string EnableAutoDonation {
            get {
                return ResourceManager.GetString("EnableAutoDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically upload all eligible games.
        /// </summary>
        public static string EnableAutoDonationTooltip {
            get {
                return ResourceManager.GetString("EnableAutoDonationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable remote logging.
        /// </summary>
        public static string EnableRemoteLogging {
            get {
                return ResourceManager.GetString("EnableRemoteLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow automatic sending of logs.
        /// </summary>
        public static string EnableRemoteLoggingTooltip {
            get {
                return ResourceManager.GetString("EnableRemoteLoggingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Wireless ADB.
        /// </summary>
        public static string EnableWirelessAdb {
            get {
                return ResourceManager.GetString("EnableWirelessAdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Name.
        /// </summary>
        public static string GameNameHeader {
            get {
                return ResourceManager.GetString("GameNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Size.
        /// </summary>
        public static string GameSizeHeader {
            get {
                return ResourceManager.GetString("GameSizeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide selected apps from donation list (select already ignored apps to inverse).
        /// </summary>
        public static string IgnoreSelectedAppsTooltip {
            get {
                return ResourceManager.GetString("IgnoreSelectedAppsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Selected.
        /// </summary>
        public static string IgnoreSelectedButton {
            get {
                return ResourceManager.GetString("IgnoreSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Games.
        /// </summary>
        public static string InstalledGamesHeader {
            get {
                return ResourceManager.GetString("InstalledGamesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Version.
        /// </summary>
        public static string InstalledVersionHeader {
            get {
                return ResourceManager.GetString("InstalledVersionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install trailers addon.
        /// </summary>
        public static string InstallTrailersAddonButton {
            get {
                return ResourceManager.GetString("InstallTrailersAddonButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        public static string LastUpdatedHeader {
            get {
                return ResourceManager.GetString("LastUpdatedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Release Name.
        /// </summary>
        public static string LatestReleaseNameHeader {
            get {
                return ResourceManager.GetString("LatestReleaseNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        public static string Limit {
            get {
                return ResourceManager.GetString("Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loader Settings.
        /// </summary>
        public static string LoaderSettingsHeader {
            get {
                return ResourceManager.GetString("LoaderSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingEllipsis {
            get {
                return ResourceManager.GetString("LoadingEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount Quest as Drive.
        /// </summary>
        public static string MountQuestButton {
            get {
                return ResourceManager.GetString("MountQuestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameHeader {
            get {
                return ResourceManager.GetString("NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backups selected.
        /// </summary>
        public static string NoBackupsSelected {
            get {
                return ResourceManager.GetString("NoBackupsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Device.
        /// </summary>
        public static string OnDeviceHeader {
            get {
                return ResourceManager.GetString("OnDeviceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Apps.
        /// </summary>
        public static string OtherAppsHeader {
            get {
                return ResourceManager.GetString("OtherAppsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity (1 day).
        /// </summary>
        public static string Popularity1DHeader {
            get {
                return ResourceManager.GetString("Popularity1DHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity (30 days).
        /// </summary>
        public static string Popularity30DHeader {
            get {
                return ResourceManager.GetString("Popularity30DHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity (7 days).
        /// </summary>
        public static string Popularity7DHeader {
            get {
                return ResourceManager.GetString("Popularity7DHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity time range.
        /// </summary>
        public static string PopularityTimeRange {
            get {
                return ResourceManager.GetString("PopularityTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred connection type.
        /// </summary>
        public static string PreferredConnectionType {
            get {
                return ResourceManager.GetString("PreferredConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Settings.
        /// </summary>
        public static string QuestSettingsHeader {
            get {
                return ResourceManager.GetString("QuestSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redownload games list.
        /// </summary>
        public static string RefreshAvailableGamesTooltip {
            get {
                return ResourceManager.GetString("RefreshAvailableGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload list of backups.
        /// </summary>
        public static string RefreshBackupsTooltip {
            get {
                return ResourceManager.GetString("RefreshBackupsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshButton {
            get {
                return ResourceManager.GetString("RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan installed apps.
        /// </summary>
        public static string RefreshInstalledAppsTooltip {
            get {
                return ResourceManager.GetString("RefreshInstalledAppsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan installed games.
        /// </summary>
        public static string RefreshInstalledGamesTooltip {
            get {
                return ResourceManager.GetString("RefreshInstalledGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Name.
        /// </summary>
        public static string ReleaseNameHeader {
            get {
                return ResourceManager.GetString("ReleaseNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload list.
        /// </summary>
        public static string ReloadListButton {
            get {
                return ResourceManager.GetString("ReloadListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Backups.
        /// </summary>
        public static string RestoreBackupsHeader {
            get {
                return ResourceManager.GetString("RestoreBackupsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Defaults.
        /// </summary>
        public static string RestoreDefaultsButton {
            get {
                return ResourceManager.GetString("RestoreDefaultsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore selected backups.
        /// </summary>
        public static string RestoreSelectedBackupsTooltip {
            get {
                return ResourceManager.GetString("RestoreSelectedBackupsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Selected.
        /// </summary>
        public static string RestoreSelectedButton {
            get {
                return ResourceManager.GetString("RestoreSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected mirror.
        /// </summary>
        public static string SelectedMirror {
            get {
                return ResourceManager.GetString("SelectedMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string SetButton {
            get {
                return ResourceManager.GetString("SetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show debug console.
        /// </summary>
        public static string ShowDebugConsole {
            get {
                return ResourceManager.GetString("ShowDebugConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hidden.
        /// </summary>
        public static string ShowHidden {
            get {
                return ResourceManager.GetString("ShowHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusHeader {
            get {
                return ResourceManager.GetString("StatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will uninstall selected apps.
        ///Are you sure you want to continue?.
        /// </summary>
        public static string UninstallAppsConfirmation {
            get {
                return ResourceManager.GetString("UninstallAppsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, uninstall.
        /// </summary>
        public static string UninstallAppsConfirmationButton {
            get {
                return ResourceManager.GetString("UninstallAppsConfirmationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall selected apps.
        /// </summary>
        public static string UninstallAppsTooltip {
            get {
                return ResourceManager.GetString("UninstallAppsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will attempt to backup data
        ///and uninstall selected games.
        ///Are you sure you want to continue?.
        /// </summary>
        public static string UninstallGamesConfirmation {
            get {
                return ResourceManager.GetString("UninstallGamesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, uninstall.
        /// </summary>
        public static string UninstallGamesConfirmationButton {
            get {
                return ResourceManager.GetString("UninstallGamesConfirmationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Selected.
        /// </summary>
        public static string UninstallSelectedButton {
            get {
                return ResourceManager.GetString("UninstallSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup and uninstall selected games.
        /// </summary>
        public static string UninstallSelectedGamesTooltip {
            get {
                return ResourceManager.GetString("UninstallSelectedGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update All.
        /// </summary>
        public static string UpdateAllButton {
            get {
                return ResourceManager.GetString("UpdateAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update all games (excluding ambiguous installs).
        /// </summary>
        public static string UpdateAllGamesTooltip {
            get {
                return ResourceManager.GetString("UpdateAllGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Selected.
        /// </summary>
        public static string UpdateSelectedButton {
            get {
                return ResourceManager.GetString("UpdateSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update selected games.
        /// </summary>
        public static string UpdateSelectedGamesTooltip {
            get {
                return ResourceManager.GetString("UpdateSelectedGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Status.
        /// </summary>
        public static string UpdateStatusHeader {
            get {
                return ResourceManager.GetString("UpdateStatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username (leave empty for default).
        /// </summary>
        public static string UsernamePlaceholder {
            get {
                return ResourceManager.GetString("UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Code.
        /// </summary>
        public static string VersionCodeHeader {
            get {
                return ResourceManager.GetString("VersionCodeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Name.
        /// </summary>
        public static string VersionNameHeader {
            get {
                return ResourceManager.GetString("VersionNameHeader", resourceCulture);
            }
        }
    }
}
