//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSideloader.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("QSideloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string DeleteSelectedButton {
            get {
                return ResourceManager.GetString("DeleteSelectedButton", resourceCulture);
            }
        }
        
        public static string DeleteSelectedBackupsTooltip {
            get {
                return ResourceManager.GetString("DeleteSelectedBackupsTooltip", resourceCulture);
            }
        }
        
        public static string RestoreSelectedButton {
            get {
                return ResourceManager.GetString("RestoreSelectedButton", resourceCulture);
            }
        }
        
        public static string RestoreSelectedBackupsTooltip {
            get {
                return ResourceManager.GetString("RestoreSelectedBackupsTooltip", resourceCulture);
            }
        }
        
        public static string DeleteBackupsConfirmation {
            get {
                return ResourceManager.GetString("DeleteBackupsConfirmation", resourceCulture);
            }
        }
        
        public static string DeleteBackupsConfirmationButton {
            get {
                return ResourceManager.GetString("DeleteBackupsConfirmationButton", resourceCulture);
            }
        }
        
        public static string RefreshButton {
            get {
                return ResourceManager.GetString("RefreshButton", resourceCulture);
            }
        }
        
        public static string DateHeader {
            get {
                return ResourceManager.GetString("DateHeader", resourceCulture);
            }
        }
        
        public static string BackupNameHeader {
            get {
                return ResourceManager.GetString("BackupNameHeader", resourceCulture);
            }
        }
        
        public static string ContentsHeader {
            get {
                return ResourceManager.GetString("ContentsHeader", resourceCulture);
            }
        }
        
        public static string RefreshBackupsTooltip {
            get {
                return ResourceManager.GetString("RefreshBackupsTooltip", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string DownloadAndInstallSelectedGamesTooltip {
            get {
                return ResourceManager.GetString("DownloadAndInstallSelectedGamesTooltip", resourceCulture);
            }
        }
        
        public static string DownloadAndInstallSelectedButton {
            get {
                return ResourceManager.GetString("DownloadAndInstallSelectedButton", resourceCulture);
            }
        }
        
        public static string DownloadSelectedButton {
            get {
                return ResourceManager.GetString("DownloadSelectedButton", resourceCulture);
            }
        }
        
        public static string DownloadSelectedGamesTooltip {
            get {
                return ResourceManager.GetString("DownloadSelectedGamesTooltip", resourceCulture);
            }
        }
        
        public static string RefreshAvailableGamesTooltip {
            get {
                return ResourceManager.GetString("RefreshAvailableGamesTooltip", resourceCulture);
            }
        }
        
        public static string GameNameHeader {
            get {
                return ResourceManager.GetString("GameNameHeader", resourceCulture);
            }
        }
        
        public static string ReleaseNameHeader {
            get {
                return ResourceManager.GetString("ReleaseNameHeader", resourceCulture);
            }
        }
        
        public static string LastUpdatedHeader {
            get {
                return ResourceManager.GetString("LastUpdatedHeader", resourceCulture);
            }
        }
        
        public static string GameSizeHeader {
            get {
                return ResourceManager.GetString("GameSizeHeader", resourceCulture);
            }
        }
        
        public static string Popularity1DHeader {
            get {
                return ResourceManager.GetString("Popularity1DHeader", resourceCulture);
            }
        }
        
        public static string Popularity7DHeader {
            get {
                return ResourceManager.GetString("Popularity7DHeader", resourceCulture);
            }
        }
        
        public static string Popularity30DHeader {
            get {
                return ResourceManager.GetString("Popularity30DHeader", resourceCulture);
            }
        }
        
        public static string OnDeviceHeader {
            get {
                return ResourceManager.GetString("OnDeviceHeader", resourceCulture);
            }
        }
        
        public static string UninstallAppsTooltip {
            get {
                return ResourceManager.GetString("UninstallAppsTooltip", resourceCulture);
            }
        }
        
        public static string UninstallSelectedButton {
            get {
                return ResourceManager.GetString("UninstallSelectedButton", resourceCulture);
            }
        }
        
        public static string UninstallAppsConfirmation {
            get {
                return ResourceManager.GetString("UninstallAppsConfirmation", resourceCulture);
            }
        }
        
        public static string UninstallAppsConfirmationButton {
            get {
                return ResourceManager.GetString("UninstallAppsConfirmationButton", resourceCulture);
            }
        }
        
        public static string RefreshInstalledAppsTooltip {
            get {
                return ResourceManager.GetString("RefreshInstalledAppsTooltip", resourceCulture);
            }
        }
        
        public static string AppNameHeader {
            get {
                return ResourceManager.GetString("AppNameHeader", resourceCulture);
            }
        }
        
        public static string VersionNameHeader {
            get {
                return ResourceManager.GetString("VersionNameHeader", resourceCulture);
            }
        }
        
        public static string VersionCodeHeader {
            get {
                return ResourceManager.GetString("VersionCodeHeader", resourceCulture);
            }
        }
        
        public static string NoBackupsSelected {
            get {
                return ResourceManager.GetString("NoBackupsSelected", resourceCulture);
            }
        }
        
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string InstalledGamesHeader {
            get {
                return ResourceManager.GetString("InstalledGamesHeader", resourceCulture);
            }
        }
        
        public static string AvailableGamesHeader {
            get {
                return ResourceManager.GetString("AvailableGamesHeader", resourceCulture);
            }
        }
        
        public static string DonateGamesHeader {
            get {
                return ResourceManager.GetString("DonateGamesHeader", resourceCulture);
            }
        }
        
        public static string OtherAppsHeader {
            get {
                return ResourceManager.GetString("OtherAppsHeader", resourceCulture);
            }
        }
        
        public static string RestoreBackupsHeader {
            get {
                return ResourceManager.GetString("RestoreBackupsHeader", resourceCulture);
            }
        }
        
        public static string ShowHidden {
            get {
                return ResourceManager.GetString("ShowHidden", resourceCulture);
            }
        }
        
        public static string DonateTooltip {
            get {
                return ResourceManager.GetString("DonateTooltip", resourceCulture);
            }
        }
        
        public static string DonateAllButton {
            get {
                return ResourceManager.GetString("DonateAllButton", resourceCulture);
            }
        }
        
        public static string DonateSelectedButton {
            get {
                return ResourceManager.GetString("DonateSelectedButton", resourceCulture);
            }
        }
        
        public static string IgnoreSelectedButton {
            get {
                return ResourceManager.GetString("IgnoreSelectedButton", resourceCulture);
            }
        }
        
        public static string IgnoreSelectedAppsTooltip {
            get {
                return ResourceManager.GetString("IgnoreSelectedAppsTooltip", resourceCulture);
            }
        }
        
        public static string NameHeader {
            get {
                return ResourceManager.GetString("NameHeader", resourceCulture);
            }
        }
        
        public static string StatusHeader {
            get {
                return ResourceManager.GetString("StatusHeader", resourceCulture);
            }
        }
        
        public static string DonateAllGamesTooltip {
            get {
                return ResourceManager.GetString("DonateAllGamesTooltip", resourceCulture);
            }
        }
        
        public static string UpdateAllGamesTooltip {
            get {
                return ResourceManager.GetString("UpdateAllGamesTooltip", resourceCulture);
            }
        }
        
        public static string UpdateSelectedGamesTooltip {
            get {
                return ResourceManager.GetString("UpdateSelectedGamesTooltip", resourceCulture);
            }
        }
        
        public static string UpdateAllButton {
            get {
                return ResourceManager.GetString("UpdateAllButton", resourceCulture);
            }
        }
        
        public static string BackupSelectedButton {
            get {
                return ResourceManager.GetString("BackupSelectedButton", resourceCulture);
            }
        }
        
        public static string BackupSelectedGamesTooltip {
            get {
                return ResourceManager.GetString("BackupSelectedGamesTooltip", resourceCulture);
            }
        }
        
        public static string BackupPartsSelectionPrompt {
            get {
                return ResourceManager.GetString("BackupPartsSelectionPrompt", resourceCulture);
            }
        }
        
        public static string BackupPartsSelectionApplicationData {
            get {
                return ResourceManager.GetString("BackupPartsSelectionApplicationData", resourceCulture);
            }
        }
        
        public static string BackupPartsSelectionApplicationFiles {
            get {
                return ResourceManager.GetString("BackupPartsSelectionApplicationFiles", resourceCulture);
            }
        }
        
        public static string BackupConfirmationButton {
            get {
                return ResourceManager.GetString("BackupConfirmationButton", resourceCulture);
            }
        }
        
        public static string UpdateSelectedButton {
            get {
                return ResourceManager.GetString("UpdateSelectedButton", resourceCulture);
            }
        }
        
        public static string UninstallSelectedGamesTooltip {
            get {
                return ResourceManager.GetString("UninstallSelectedGamesTooltip", resourceCulture);
            }
        }
        
        public static string UninstallGamesConfirmation {
            get {
                return ResourceManager.GetString("UninstallGamesConfirmation", resourceCulture);
            }
        }
        
        public static string UninstallGamesConfirmationButton {
            get {
                return ResourceManager.GetString("UninstallGamesConfirmationButton", resourceCulture);
            }
        }
        
        public static string RefreshInstalledGamesTooltip {
            get {
                return ResourceManager.GetString("RefreshInstalledGamesTooltip", resourceCulture);
            }
        }
        
        public static string InstalledVersionHeader {
            get {
                return ResourceManager.GetString("InstalledVersionHeader", resourceCulture);
            }
        }
        
        public static string LatestReleaseNameHeader {
            get {
                return ResourceManager.GetString("LatestReleaseNameHeader", resourceCulture);
            }
        }
        
        public static string UpdateStatusHeader {
            get {
                return ResourceManager.GetString("UpdateStatusHeader", resourceCulture);
            }
        }
        
        public static string LoadingEllipsis {
            get {
                return ResourceManager.GetString("LoadingEllipsis", resourceCulture);
            }
        }
        
        public static string DeviceInfoColon {
            get {
                return ResourceManager.GetString("DeviceInfoColon", resourceCulture);
            }
        }
        
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        public static string BatteryLevel {
            get {
                return ResourceManager.GetString("BatteryLevel", resourceCulture);
            }
        }
        
        public static string EnableWirelessAdb {
            get {
                return ResourceManager.GetString("EnableWirelessAdb", resourceCulture);
            }
        }
        
        public static string DeviceList {
            get {
                return ResourceManager.GetString("DeviceList", resourceCulture);
            }
        }
        
        public static string CurrentDeviceSerial {
            get {
                return ResourceManager.GetString("CurrentDeviceSerial", resourceCulture);
            }
        }
        
        public static string QuestSettingsHeader {
            get {
                return ResourceManager.GetString("QuestSettingsHeader", resourceCulture);
            }
        }
        
        public static string UsernamePlaceholder {
            get {
                return ResourceManager.GetString("UsernamePlaceholder", resourceCulture);
            }
        }
        
        public static string MountQuestButton {
            get {
                return ResourceManager.GetString("MountQuestButton", resourceCulture);
            }
        }
        
        public static string ApplySettingsButton {
            get {
                return ResourceManager.GetString("ApplySettingsButton", resourceCulture);
            }
        }
        
        public static string LoaderSettingsHeader {
            get {
                return ResourceManager.GetString("LoaderSettingsHeader", resourceCulture);
            }
        }
        
        public static string RestoreDefaultsButton {
            get {
                return ResourceManager.GetString("RestoreDefaultsButton", resourceCulture);
            }
        }
        
        public static string CheckUpdatesAutomatically {
            get {
                return ResourceManager.GetString("CheckUpdatesAutomatically", resourceCulture);
            }
        }
        
        public static string CheckUpdatesNowButton {
            get {
                return ResourceManager.GetString("CheckUpdatesNowButton", resourceCulture);
            }
        }
        
        public static string PreferredConnectionType {
            get {
                return ResourceManager.GetString("PreferredConnectionType", resourceCulture);
            }
        }
        
        public static string SelectedMirror {
            get {
                return ResourceManager.GetString("SelectedMirror", resourceCulture);
            }
        }
        
        public static string ReloadListButton {
            get {
                return ResourceManager.GetString("ReloadListButton", resourceCulture);
            }
        }
        
        public static string PopularityTimeRange {
            get {
                return ResourceManager.GetString("PopularityTimeRange", resourceCulture);
            }
        }
        
        public static string DownloadsLocation {
            get {
                return ResourceManager.GetString("DownloadsLocation", resourceCulture);
            }
        }
        
        public static string BackupsLocation {
            get {
                return ResourceManager.GetString("BackupsLocation", resourceCulture);
            }
        }
        
        public static string DownloaderBandwidthLimit {
            get {
                return ResourceManager.GetString("DownloaderBandwidthLimit", resourceCulture);
            }
        }
        
        public static string DownloaderBandwidthLimitTooltip {
            get {
                return ResourceManager.GetString("DownloaderBandwidthLimitTooltip", resourceCulture);
            }
        }
        
        public static string DownloadsPruningPolicy {
            get {
                return ResourceManager.GetString("DownloadsPruningPolicy", resourceCulture);
            }
        }
        
        public static string EnableRemoteLogging {
            get {
                return ResourceManager.GetString("EnableRemoteLogging", resourceCulture);
            }
        }
        
        public static string EnableRemoteLoggingTooltip {
            get {
                return ResourceManager.GetString("EnableRemoteLoggingTooltip", resourceCulture);
            }
        }
        
        public static string EnableAutoDonation {
            get {
                return ResourceManager.GetString("EnableAutoDonation", resourceCulture);
            }
        }
        
        public static string EnableAutoDonationTooltip {
            get {
                return ResourceManager.GetString("EnableAutoDonationTooltip", resourceCulture);
            }
        }
        
        public static string ShowDebugConsole {
            get {
                return ResourceManager.GetString("ShowDebugConsole", resourceCulture);
            }
        }
        
        public static string InstallTrailersAddonButton {
            get {
                return ResourceManager.GetString("InstallTrailersAddonButton", resourceCulture);
            }
        }
        
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        public static string CopyInstallationIdButton {
            get {
                return ResourceManager.GetString("CopyInstallationIdButton", resourceCulture);
            }
        }
        
        public static string Limit {
            get {
                return ResourceManager.GetString("Limit", resourceCulture);
            }
        }
        
        public static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        public static string SetButton {
            get {
                return ResourceManager.GetString("SetButton", resourceCulture);
            }
        }
        
        public static string DownloadAndInstallButton {
            get {
                return ResourceManager.GetString("DownloadAndInstallButton", resourceCulture);
            }
        }
        
        public static string OculusStoreLinkTooltip {
            get {
                return ResourceManager.GetString("OculusStoreLinkTooltip", resourceCulture);
            }
        }
        
        public static string DownloadSize {
            get {
                return ResourceManager.GetString("DownloadSize", resourceCulture);
            }
        }
        
        public static string StoreRating {
            get {
                return ResourceManager.GetString("StoreRating", resourceCulture);
            }
        }
        
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        public static string DescriptionColon {
            get {
                return ResourceManager.GetString("DescriptionColon", resourceCulture);
            }
        }
        
        public static string DownloadButton {
            get {
                return ResourceManager.GetString("DownloadButton", resourceCulture);
            }
        }
        
        public static string ErrorGameDetailsDialog {
            get {
                return ResourceManager.GetString("ErrorGameDetailsDialog", resourceCulture);
            }
        }
        
        public static string ErrorAutoDonation {
            get {
                return ResourceManager.GetString("ErrorAutoDonation", resourceCulture);
            }
        }
        
        public static string ErrorAddingTask {
            get {
                return ResourceManager.GetString("ErrorAddingTask", resourceCulture);
            }
        }
        
        public static string CopiedToClipboardHeader {
            get {
                return ResourceManager.GetString("CopiedToClipboardHeader", resourceCulture);
            }
        }
        
        public static string ExceptionCopiedToClipboard {
            get {
                return ResourceManager.GetString("ExceptionCopiedToClipboard", resourceCulture);
            }
        }
        
        public static string AdbAuthorizationDialogTitle {
            get {
                return ResourceManager.GetString("AdbAuthorizationDialogTitle", resourceCulture);
            }
        }
        
        public static string AdbAuthorizationDialogText {
            get {
                return ResourceManager.GetString("AdbAuthorizationDialogText", resourceCulture);
            }
        }
        
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        public static string AdbConnectionDialogTitle {
            get {
                return ResourceManager.GetString("AdbConnectionDialogTitle", resourceCulture);
            }
        }
        
        public static string AdbConnectionDialogText {
            get {
                return ResourceManager.GetString("AdbConnectionDialogText", resourceCulture);
            }
        }
        
        public static string AdbConnectionDialogTextWin {
            get {
                return ResourceManager.GetString("AdbConnectionDialogTextWin", resourceCulture);
            }
        }
        
        public static string ForceDevicesRescanButton {
            get {
                return ResourceManager.GetString("ForceDevicesRescanButton", resourceCulture);
            }
        }
        
        public static string CopyToClipboardButton {
            get {
                return ResourceManager.GetString("CopyToClipboardButton", resourceCulture);
            }
        }
        
        public static string AdbDevicesCopiedToClipboard {
            get {
                return ResourceManager.GetString("AdbDevicesCopiedToClipboard", resourceCulture);
            }
        }
        
        public static string ReloadButton {
            get {
                return ResourceManager.GetString("ReloadButton", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string AdbDevicesDialogTitle {
            get {
                return ResourceManager.GetString("AdbDevicesDialogTitle", resourceCulture);
            }
        }
        
        public static string ClickToCancel {
            get {
                return ResourceManager.GetString("ClickToCancel", resourceCulture);
            }
        }
        
        public static string TaskFailed {
            get {
                return ResourceManager.GetString("TaskFailed", resourceCulture);
            }
        }
        
        public static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        public static string InstallFailed {
            get {
                return ResourceManager.GetString("InstallFailed", resourceCulture);
            }
        }
        
        public static string DownloadSuccess {
            get {
                return ResourceManager.GetString("DownloadSuccess", resourceCulture);
            }
        }
        
        public static string InstallSuccess {
            get {
                return ResourceManager.GetString("InstallSuccess", resourceCulture);
            }
        }
        
        public static string UninstallFailed {
            get {
                return ResourceManager.GetString("UninstallFailed", resourceCulture);
            }
        }
        
        public static string UninstallSuccess {
            get {
                return ResourceManager.GetString("UninstallSuccess", resourceCulture);
            }
        }
        
        public static string BackupFailed {
            get {
                return ResourceManager.GetString("BackupFailed", resourceCulture);
            }
        }
        
        public static string BackupSuccess {
            get {
                return ResourceManager.GetString("BackupSuccess", resourceCulture);
            }
        }
        
        public static string RestoreFailed {
            get {
                return ResourceManager.GetString("RestoreFailed", resourceCulture);
            }
        }
        
        public static string RestoreSuccess {
            get {
                return ResourceManager.GetString("RestoreSuccess", resourceCulture);
            }
        }
        
        public static string PullingFromDevice {
            get {
                return ResourceManager.GetString("PullingFromDevice", resourceCulture);
            }
        }
        
        public static string PreparingToUpload {
            get {
                return ResourceManager.GetString("PreparingToUpload", resourceCulture);
            }
        }
        
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        public static string DonationFailed {
            get {
                return ResourceManager.GetString("DonationFailed", resourceCulture);
            }
        }
        
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        public static string UploadSuccess {
            get {
                return ResourceManager.GetString("UploadSuccess", resourceCulture);
            }
        }
        
        public static string AlreadyInstalled {
            get {
                return ResourceManager.GetString("AlreadyInstalled", resourceCulture);
            }
        }
        
        public static string DownloadQueued {
            get {
                return ResourceManager.GetString("DownloadQueued", resourceCulture);
            }
        }
        
        public static string CalculatingSize {
            get {
                return ResourceManager.GetString("CalculatingSize", resourceCulture);
            }
        }
        
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        public static string InstallQueued {
            get {
                return ResourceManager.GetString("InstallQueued", resourceCulture);
            }
        }
        
        public static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        public static string DeletingDownloadedFiles {
            get {
                return ResourceManager.GetString("DeletingDownloadedFiles", resourceCulture);
            }
        }
        
        public static string FailedToDeleteDownloadedFiles {
            get {
                return ResourceManager.GetString("FailedToDeleteDownloadedFiles", resourceCulture);
            }
        }
        
        public static string UninstallQueued {
            get {
                return ResourceManager.GetString("UninstallQueued", resourceCulture);
            }
        }
        
        public static string Uninstalling {
            get {
                return ResourceManager.GetString("Uninstalling", resourceCulture);
            }
        }
        
        public static string CreatingBackup {
            get {
                return ResourceManager.GetString("CreatingBackup", resourceCulture);
            }
        }
        
        public static string RestoringBackup {
            get {
                return ResourceManager.GetString("RestoringBackup", resourceCulture);
            }
        }
        
        public static string ClickToDismiss {
            get {
                return ResourceManager.GetString("ClickToDismiss", resourceCulture);
            }
        }
        
        public static string TaskNameFailed {
            get {
                return ResourceManager.GetString("TaskNameFailed", resourceCulture);
            }
        }
        
        public static string FailedNoDeviceConnection {
            get {
                return ResourceManager.GetString("FailedNoDeviceConnection", resourceCulture);
            }
        }
        
        public static string RestoreQueued {
            get {
                return ResourceManager.GetString("RestoreQueued", resourceCulture);
            }
        }
        
        public static string InstallingApk {
            get {
                return ResourceManager.GetString("InstallingApk", resourceCulture);
            }
        }
        
        public static string PerformingCustomInstall {
            get {
                return ResourceManager.GetString("PerformingCustomInstall", resourceCulture);
            }
        }
        
        public static string PushingObbFiles {
            get {
                return ResourceManager.GetString("PushingObbFiles", resourceCulture);
            }
        }
        
        public static string CleaningUp {
            get {
                return ResourceManager.GetString("CleaningUp", resourceCulture);
            }
        }
        
        public static string IncompatibleUpdateReinstalling {
            get {
                return ResourceManager.GetString("IncompatibleUpdateReinstalling", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string NoDeviceConnection {
            get {
                return ResourceManager.GetString("NoDeviceConnection", resourceCulture);
            }
        }
        
        public static string AdbUnauthorized {
            get {
                return ResourceManager.GetString("AdbUnauthorized", resourceCulture);
            }
        }
        
        public static string MoreInfoButton {
            get {
                return ResourceManager.GetString("MoreInfoButton", resourceCulture);
            }
        }
        
        public static string TasksHeader {
            get {
                return ResourceManager.GetString("TasksHeader", resourceCulture);
            }
        }
        
        public static string DragDropPanelText {
            get {
                return ResourceManager.GetString("DragDropPanelText", resourceCulture);
            }
        }
        
        public static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        public static string NewApp {
            get {
                return ResourceManager.GetString("NewApp", resourceCulture);
            }
        }
        
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        public static string Donated {
            get {
                return ResourceManager.GetString("Donated", resourceCulture);
            }
        }
        
        public static string Ignored {
            get {
                return ResourceManager.GetString("Ignored", resourceCulture);
            }
        }
        
        public static string Blacklisted {
            get {
                return ResourceManager.GetString("Blacklisted", resourceCulture);
            }
        }
        
        public static string FailedToStartAdbServer {
            get {
                return ResourceManager.GetString("FailedToStartAdbServer", resourceCulture);
            }
        }
        
        public static string NoMirrorsAvailable {
            get {
                return ResourceManager.GetString("NoMirrorsAvailable", resourceCulture);
            }
        }
        
        public static string FailedToLoadPopularity {
            get {
                return ResourceManager.GetString("FailedToLoadPopularity", resourceCulture);
            }
        }
        
        public static string ErrorRefreshingAvailableGames {
            get {
                return ResourceManager.GetString("ErrorRefreshingAvailableGames", resourceCulture);
            }
        }
        
        public static string NoGamesSelected {
            get {
                return ResourceManager.GetString("NoGamesSelected", resourceCulture);
            }
        }
        
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        public static string AppliedDeviceSettings {
            get {
                return ResourceManager.GetString("AppliedDeviceSettings", resourceCulture);
            }
        }
        
        public static string DeviceStorageMounted {
            get {
                return ResourceManager.GetString("DeviceStorageMounted", resourceCulture);
            }
        }
        
        public static string NoAppsSelected {
            get {
                return ResourceManager.GetString("NoAppsSelected", resourceCulture);
            }
        }
        
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        public static string NoAppsToDonate {
            get {
                return ResourceManager.GetString("NoAppsToDonate", resourceCulture);
            }
        }
        
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        public static string AppsAddedToIgnore {
            get {
                return ResourceManager.GetString("AppsAddedToIgnore", resourceCulture);
            }
        }
        
        public static string AppsRemovedFromIgnore {
            get {
                return ResourceManager.GetString("AppsRemovedFromIgnore", resourceCulture);
            }
        }
        
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        public static string NoGamesToUpdate {
            get {
                return ResourceManager.GetString("NoGamesToUpdate", resourceCulture);
            }
        }
        
        public static string NoGamesToUpdateSkipped {
            get {
                return ResourceManager.GetString("NoGamesToUpdateSkipped", resourceCulture);
            }
        }
        
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        public static string RestoredDefaultSettings {
            get {
                return ResourceManager.GetString("RestoredDefaultSettings", resourceCulture);
            }
        }
        
        public static string LocationNotWritable {
            get {
                return ResourceManager.GetString("LocationNotWritable", resourceCulture);
            }
        }
        
        public static string DownloadsLocationSet {
            get {
                return ResourceManager.GetString("DownloadsLocationSet", resourceCulture);
            }
        }
        
        public static string BackupsLocationSet {
            get {
                return ResourceManager.GetString("BackupsLocationSet", resourceCulture);
            }
        }
        
        public static string BandwidthLimitSet {
            get {
                return ResourceManager.GetString("BandwidthLimitSet", resourceCulture);
            }
        }
        
        public static string BandwidthLimitRemoved {
            get {
                return ResourceManager.GetString("BandwidthLimitRemoved", resourceCulture);
            }
        }
        
        public static string InstallationIdCopied {
            get {
                return ResourceManager.GetString("InstallationIdCopied", resourceCulture);
            }
        }
        
        public static string ApplicationRestartNeededForSetting {
            get {
                return ResourceManager.GetString("ApplicationRestartNeededForSetting", resourceCulture);
            }
        }
        
        public static string ErrorCheckingDeviceConnection {
            get {
                return ResourceManager.GetString("ErrorCheckingDeviceConnection", resourceCulture);
            }
        }
        
        public static string ErrorNotifyingDeviceStateChange {
            get {
                return ResourceManager.GetString("ErrorNotifyingDeviceStateChange", resourceCulture);
            }
        }
        
        public static string FailedToEnableWirelessAdb {
            get {
                return ResourceManager.GetString("FailedToEnableWirelessAdb", resourceCulture);
            }
        }
        
        public static string ErrorRefreshingInstalledGames {
            get {
                return ResourceManager.GetString("ErrorRefreshingInstalledGames", resourceCulture);
            }
        }
        
        public static string ErrorApplyingDeviceSettings {
            get {
                return ResourceManager.GetString("ErrorApplyingDeviceSettings", resourceCulture);
            }
        }
        
        public static string FailedToLoadDeviceSettings {
            get {
                return ResourceManager.GetString("FailedToLoadDeviceSettings", resourceCulture);
            }
        }
        
        public static string FailedToInitVideoPlayer {
            get {
                return ResourceManager.GetString("FailedToInitVideoPlayer", resourceCulture);
            }
        }
        
        public static string ErrorCheckingForUpdates {
            get {
                return ResourceManager.GetString("ErrorCheckingForUpdates", resourceCulture);
            }
        }
        
        public static string FailedToSwitchMirror {
            get {
                return ResourceManager.GetString("FailedToSwitchMirror", resourceCulture);
            }
        }
        
        public static string FailedToSaveSettings {
            get {
                return ResourceManager.GetString("FailedToSaveSettings", resourceCulture);
            }
        }
        
        public static string FailedToReloadMirrorList {
            get {
                return ResourceManager.GetString("FailedToReloadMirrorList", resourceCulture);
            }
        }
        
        public static string ExtractSelected {
            get {
                return ResourceManager.GetString("ExtractSelected", resourceCulture);
            }
        }
        
        public static string ExtractAppsTooltip {
            get {
                return ResourceManager.GetString("ExtractAppsTooltip", resourceCulture);
            }
        }
        
        public static string Extract {
            get {
                return ResourceManager.GetString("Extract", resourceCulture);
            }
        }
        
        public static string ExtractSuccess {
            get {
                return ResourceManager.GetString("ExtractSuccess", resourceCulture);
            }
        }
        
        public static string ExtractionFailed {
            get {
                return ResourceManager.GetString("ExtractionFailed", resourceCulture);
            }
        }
        
        public static string SelectDownloadsFolder {
            get {
                return ResourceManager.GetString("SelectDownloadsFolder", resourceCulture);
            }
        }
        
        public static string SelectBackupsFolder {
            get {
                return ResourceManager.GetString("SelectBackupsFolder", resourceCulture);
            }
        }
        
        public static string SelectDestinationFolder {
            get {
                return ResourceManager.GetString("SelectDestinationFolder", resourceCulture);
            }
        }
        
        public static string CouldntVerifyVip {
            get {
                return ResourceManager.GetString("CouldntVerifyVip", resourceCulture);
            }
        }
        
        public static string BackupQueued {
            get {
                return ResourceManager.GetString("BackupQueued", resourceCulture);
            }
        }
        
        public static string ErrorApkInfo {
            get {
                return ResourceManager.GetString("ErrorApkInfo", resourceCulture);
            }
        }
        
        public static string CopyLinkButton {
            get {
                return ResourceManager.GetString("CopyLinkButton", resourceCulture);
            }
        }
        
        public static string LinkCopiedToClipboard {
            get {
                return ResourceManager.GetString("LinkCopiedToClipboard", resourceCulture);
            }
        }
        
        public static string CouldntCreateLink {
            get {
                return ResourceManager.GetString("CouldntCreateLink", resourceCulture);
            }
        }
        
        public static string SkipBackup {
            get {
                return ResourceManager.GetString("SkipBackup", resourceCulture);
            }
        }
        
        public static string ClickToSeeDetails {
            get {
                return ResourceManager.GetString("ClickToSeeDetails", resourceCulture);
            }
        }
        
        public static string RescanningDevices {
            get {
                return ResourceManager.GetString("RescanningDevices", resourceCulture);
            }
        }
        
        public static string ErrorRescanningDevices {
            get {
                return ResourceManager.GetString("ErrorRescanningDevices", resourceCulture);
            }
        }
        
        public static string ErrorRefreshingDeviceInfo {
            get {
                return ResourceManager.GetString("ErrorRefreshingDeviceInfo", resourceCulture);
            }
        }
        
        public static string FailedToResetAdbKeys {
            get {
                return ResourceManager.GetString("FailedToResetAdbKeys", resourceCulture);
            }
        }
        
        public static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        public static string DeviceReconnectCompleted {
            get {
                return ResourceManager.GetString("DeviceReconnectCompleted", resourceCulture);
            }
        }
        
        public static string ErrorReconnectingDevice {
            get {
                return ResourceManager.GetString("ErrorReconnectingDevice", resourceCulture);
            }
        }
        
        public static string RestartingAdbServer {
            get {
                return ResourceManager.GetString("RestartingAdbServer", resourceCulture);
            }
        }
        
        public static string AdbKeysReset {
            get {
                return ResourceManager.GetString("AdbKeysReset", resourceCulture);
            }
        }
        
        public static string LeftoverApksCleanupCompleted {
            get {
                return ResourceManager.GetString("LeftoverApksCleanupCompleted", resourceCulture);
            }
        }
        
        public static string ErrorCleaningUpLeftoverApks {
            get {
                return ResourceManager.GetString("ErrorCleaningUpLeftoverApks", resourceCulture);
            }
        }
        
        public static string RescanDevices {
            get {
                return ResourceManager.GetString("RescanDevices", resourceCulture);
            }
        }
        
        public static string ReconnectToDevice {
            get {
                return ResourceManager.GetString("ReconnectToDevice", resourceCulture);
            }
        }
        
        public static string RestartAdbServer {
            get {
                return ResourceManager.GetString("RestartAdbServer", resourceCulture);
            }
        }
        
        public static string ResetAdbKeys {
            get {
                return ResourceManager.GetString("ResetAdbKeys", resourceCulture);
            }
        }
        
        public static string ForceCleanupPackage {
            get {
                return ResourceManager.GetString("ForceCleanupPackage", resourceCulture);
            }
        }
        
        public static string CleanLeftoverApks {
            get {
                return ResourceManager.GetString("CleanLeftoverApks", resourceCulture);
            }
        }
        
        public static string TroubleshootingOptions {
            get {
                return ResourceManager.GetString("TroubleshootingOptions", resourceCulture);
            }
        }
        
        public static string PullPicturesAndVideos {
            get {
                return ResourceManager.GetString("PullPicturesAndVideos", resourceCulture);
            }
        }
        
        public static string PullPicturesAndVideosSuccess {
            get {
                return ResourceManager.GetString("PullPicturesAndVideosSuccess", resourceCulture);
            }
        }
        
        public static string PullingPicturesAndVideosTooltip {
            get {
                return ResourceManager.GetString("PullingPicturesAndVideosTooltip", resourceCulture);
            }
        }
        
        public static string PullPicturesAndVideosFailed {
            get {
                return ResourceManager.GetString("PullPicturesAndVideosFailed", resourceCulture);
            }
        }
        
        public static string PullingPicturesAndVideos {
            get {
                return ResourceManager.GetString("PullingPicturesAndVideos", resourceCulture);
            }
        }
        
        public static string EnableTaskAutoDismiss {
            get {
                return ResourceManager.GetString("EnableTaskAutoDismiss", resourceCulture);
            }
        }
        
        public static string EnableTaskAutoDismissTooltip {
            get {
                return ResourceManager.GetString("EnableTaskAutoDismissTooltip", resourceCulture);
            }
        }
        
        public static string TaskAutoDismissDelay {
            get {
                return ResourceManager.GetString("TaskAutoDismissDelay", resourceCulture);
            }
        }
        
        public static string TaskAutoDismissDelaySet {
            get {
                return ResourceManager.GetString("TaskAutoDismissDelaySet", resourceCulture);
            }
        }
        
        public static string InputNotANumber {
            get {
                return ResourceManager.GetString("InputNotANumber", resourceCulture);
            }
        }
        
        public static string SelectSharingMethod {
            get {
                return ResourceManager.GetString("SelectSharingMethod", resourceCulture);
            }
        }
        
        public static string DonationsAvailable {
            get {
                return ResourceManager.GetString("DonationsAvailable", resourceCulture);
            }
        }
        
        public static string DonateSelectiveButton {
            get {
                return ResourceManager.GetString("DonateSelectiveButton", resourceCulture);
            }
        }
        
        public static string DisableDonationNotification {
            get {
                return ResourceManager.GetString("DisableDonationNotification", resourceCulture);
            }
        }
        
        public static string DisableDonationNotificationTooltip {
            get {
                return ResourceManager.GetString("DisableDonationNotificationTooltip", resourceCulture);
            }
        }
        
        public static string SelectSharingMethodSubtext {
            get {
                return ResourceManager.GetString("SelectSharingMethodSubtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Name.
        /// </summary>
        public static string VersionNameHeader {
            get {
                return ResourceManager.GetString("VersionNameHeader", resourceCulture);
            }
        }
    }
}
