//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSideloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QSideloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB authorization is required to connect to the device.
        ///Please allow USB debugging in your headset..
        /// </summary>
        public static string AdbAuthorizationDialogText {
            get {
                return ResourceManager.GetString("AdbAuthorizationDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB authorization.
        /// </summary>
        public static string AdbAuthorizationDialogTitle {
            get {
                return ResourceManager.GetString("AdbAuthorizationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB connection check.
        /// </summary>
        public static string AdbConnectionCheckHeader {
            get {
                return ResourceManager.GetString("AdbConnectionCheckHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for connected device....
        /// </summary>
        public static string AdbConnectionCheckText {
            get {
                return ResourceManager.GetString("AdbConnectionCheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connected device found. Make sure you have done the following:
        ///1. Enable developer mode
        ///2. Connect your headset to your computer using usb data cable
        ///3. Close any possibly conflicting apps (SideQuest for example)
        ///
        ///You may use {0} for downloads without connecting to a device..
        /// </summary>
        public static string AdbConnectionDialogText {
            get {
                return ResourceManager.GetString("AdbConnectionDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connected device found. Make sure you have done the following:
        ///1. Enable developer mode
        ///2. Install Oculus ADB driver
        ///3. Connect your headset to your computer using usb data cable
        ///4. Close any possibly conflicting apps (SideQuest or BlueStacks for example)
        ///
        ///You may use {0} for downloads without connecting to a device..
        /// </summary>
        public static string AdbConnectionDialogTextWin {
            get {
                return ResourceManager.GetString("AdbConnectionDialogTextWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device connection.
        /// </summary>
        public static string AdbConnectionDialogTitle {
            get {
                return ResourceManager.GetString("AdbConnectionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The devices list has been copied to clipboard.
        /// </summary>
        public static string AdbDevicesCopiedToClipboard {
            get {
                return ResourceManager.GetString("AdbDevicesCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB devices.
        /// </summary>
        public static string AdbDevicesDialogTitle {
            get {
                return ResourceManager.GetString("AdbDevicesDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB unauthorized.
        /// </summary>
        public static string AdbUnauthorized {
            get {
                return ResourceManager.GetString("AdbUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already installed.
        /// </summary>
        public static string AlreadyInstalled {
            get {
                return ResourceManager.GetString("AlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application restart is needed to apply this change.
        /// </summary>
        public static string ApplicationRestartNeededForSetting {
            get {
                return ResourceManager.GetString("ApplicationRestartNeededForSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied device settings.
        /// </summary>
        public static string AppliedDeviceSettings {
            get {
                return ResourceManager.GetString("AppliedDeviceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Settings.
        /// </summary>
        public static string ApplySettingsButton {
            get {
                return ResourceManager.GetString("ApplySettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Name.
        /// </summary>
        public static string AppNameHeader {
            get {
                return ResourceManager.GetString("AppNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} apps added to ignore list.
        /// </summary>
        public static string AppsAddedToIgnore {
            get {
                return ResourceManager.GetString("AppsAddedToIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} apps removed from ignore list.
        /// </summary>
        public static string AppsRemovedFromIgnore {
            get {
                return ResourceManager.GetString("AppsRemovedFromIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Games.
        /// </summary>
        public static string AvailableGamesHeader {
            get {
                return ResourceManager.GetString("AvailableGamesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run backup.
        /// </summary>
        public static string BackupConfirmationButton {
            get {
                return ResourceManager.GetString("BackupConfirmationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup failed.
        /// </summary>
        public static string BackupFailed {
            get {
                return ResourceManager.GetString("BackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Name.
        /// </summary>
        public static string BackupNameHeader {
            get {
                return ResourceManager.GetString("BackupNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application data (saves and settings).
        /// </summary>
        public static string BackupPartsSelectionApplicationData {
            get {
                return ResourceManager.GetString("BackupPartsSelectionApplicationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application files (APK + OBB).
        /// </summary>
        public static string BackupPartsSelectionApplicationFiles {
            get {
                return ResourceManager.GetString("BackupPartsSelectionApplicationFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select parts you want to backup:.
        /// </summary>
        public static string BackupPartsSelectionPrompt {
            get {
                return ResourceManager.GetString("BackupPartsSelectionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup queued.
        /// </summary>
        public static string BackupQueued {
            get {
                return ResourceManager.GetString("BackupQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Selected.
        /// </summary>
        public static string BackupSelectedButton {
            get {
                return ResourceManager.GetString("BackupSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup selected games.
        /// </summary>
        public static string BackupSelectedGamesTooltip {
            get {
                return ResourceManager.GetString("BackupSelectedGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups location.
        /// </summary>
        public static string BackupsLocation {
            get {
                return ResourceManager.GetString("BackupsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New backups location set.
        /// </summary>
        public static string BackupsLocationSet {
            get {
                return ResourceManager.GetString("BackupsLocationSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup created.
        /// </summary>
        public static string BackupSuccess {
            get {
                return ResourceManager.GetString("BackupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloader bandwidth limit removed.
        /// </summary>
        public static string BandwidthLimitRemoved {
            get {
                return ResourceManager.GetString("BandwidthLimitRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloader bandwidth limit set.
        /// </summary>
        public static string BandwidthLimitSet {
            get {
                return ResourceManager.GetString("BandwidthLimitSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery level.
        /// </summary>
        public static string BatteryLevel {
            get {
                return ResourceManager.GetString("BatteryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklisted.
        /// </summary>
        public static string Blacklisted {
            get {
                return ResourceManager.GetString("Blacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating size.
        /// </summary>
        public static string CalculatingSize {
            get {
                return ResourceManager.GetString("CalculatingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates automatically.
        /// </summary>
        public static string CheckUpdatesAutomatically {
            get {
                return ResourceManager.GetString("CheckUpdatesAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Now.
        /// </summary>
        public static string CheckUpdatesNowButton {
            get {
                return ResourceManager.GetString("CheckUpdatesNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up.
        /// </summary>
        public static string CleaningUp {
            get {
                return ResourceManager.GetString("CleaningUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to cancel.
        /// </summary>
        public static string ClickToCancel {
            get {
                return ResourceManager.GetString("ClickToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to dismiss.
        /// </summary>
        public static string ClickToDismiss {
            get {
                return ResourceManager.GetString("ClickToDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        public static string ContentsHeader {
            get {
                return ResourceManager.GetString("ContentsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard.
        /// </summary>
        public static string CopiedToClipboardHeader {
            get {
                return ResourceManager.GetString("CopiedToClipboardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy installation ID.
        /// </summary>
        public static string CopyInstallationIdButton {
            get {
                return ResourceManager.GetString("CopyInstallationIdButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy link.
        /// </summary>
        public static string CopyLinkButton {
            get {
                return ResourceManager.GetString("CopyLinkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string CopyToClipboardButton {
            get {
                return ResourceManager.GetString("CopyToClipboardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t create link.
        /// </summary>
        public static string CouldntCreateLink {
            get {
                return ResourceManager.GetString("CouldntCreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t verify VIP access.
        /// </summary>
        public static string CouldntVerifyVip {
            get {
                return ResourceManager.GetString("CouldntVerifyVip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating backup.
        /// </summary>
        public static string CreatingBackup {
            get {
                return ResourceManager.GetString("CreatingBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current device serial.
        /// </summary>
        public static string CurrentDeviceSerial {
            get {
                return ResourceManager.GetString("CurrentDeviceSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateHeader {
            get {
                return ResourceManager.GetString("DateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will delete selected backups.
        ///Are you sure you want to continue?.
        /// </summary>
        public static string DeleteBackupsConfirmation {
            get {
                return ResourceManager.GetString("DeleteBackupsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete.
        /// </summary>
        public static string DeleteBackupsConfirmationButton {
            get {
                return ResourceManager.GetString("DeleteBackupsConfirmationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected backups.
        /// </summary>
        public static string DeleteSelectedBackupsTooltip {
            get {
                return ResourceManager.GetString("DeleteSelectedBackupsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected.
        /// </summary>
        public static string DeleteSelectedButton {
            get {
                return ResourceManager.GetString("DeleteSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting downloaded files.
        /// </summary>
        public static string DeletingDownloadedFiles {
            get {
                return ResourceManager.GetString("DeletingDownloadedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string DescriptionColon {
            get {
                return ResourceManager.GetString("DescriptionColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Info:.
        /// </summary>
        public static string DeviceInfoColon {
            get {
                return ResourceManager.GetString("DeviceInfoColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device list.
        /// </summary>
        public static string DeviceList {
            get {
                return ResourceManager.GetString("DeviceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device storage mounted.
        /// </summary>
        public static string DeviceStorageMounted {
            get {
                return ResourceManager.GetString("DeviceStorageMounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate All.
        /// </summary>
        public static string DonateAllButton {
            get {
                return ResourceManager.GetString("DonateAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload all eligible games.
        /// </summary>
        public static string DonateAllGamesTooltip {
            get {
                return ResourceManager.GetString("DonateAllGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donated.
        /// </summary>
        public static string Donated {
            get {
                return ResourceManager.GetString("Donated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate Games.
        /// </summary>
        public static string DonateGamesHeader {
            get {
                return ResourceManager.GetString("DonateGamesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate Selected.
        /// </summary>
        public static string DonateSelectedButton {
            get {
                return ResourceManager.GetString("DonateSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload selected games.
        /// </summary>
        public static string DonateTooltip {
            get {
                return ResourceManager.GetString("DonateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation failed.
        /// </summary>
        public static string DonationFailed {
            get {
                return ResourceManager.GetString("DonationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download &amp; Install.
        /// </summary>
        public static string DownloadAndInstallButton {
            get {
                return ResourceManager.GetString("DownloadAndInstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download &amp; Install Selected.
        /// </summary>
        public static string DownloadAndInstallSelectedButton {
            get {
                return ResourceManager.GetString("DownloadAndInstallSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and install selected games.
        /// </summary>
        public static string DownloadAndInstallSelectedGamesTooltip {
            get {
                return ResourceManager.GetString("DownloadAndInstallSelectedGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DownloadButton {
            get {
                return ResourceManager.GetString("DownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download/upload bandwidth limit.
        /// </summary>
        public static string DownloaderBandwidthLimit {
            get {
                return ResourceManager.GetString("DownloaderBandwidthLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit in KiB/s, or use suffix B|K|M|G|T|P (leave empty for unlimited).
        /// </summary>
        public static string DownloaderBandwidthLimitTooltip {
            get {
                return ResourceManager.GetString("DownloaderBandwidthLimitTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed.
        /// </summary>
        public static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download queued.
        /// </summary>
        public static string DownloadQueued {
            get {
                return ResourceManager.GetString("DownloadQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Selected.
        /// </summary>
        public static string DownloadSelectedButton {
            get {
                return ResourceManager.GetString("DownloadSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download selected games.
        /// </summary>
        public static string DownloadSelectedGamesTooltip {
            get {
                return ResourceManager.GetString("DownloadSelectedGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download size.
        /// </summary>
        public static string DownloadSize {
            get {
                return ResourceManager.GetString("DownloadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads location.
        /// </summary>
        public static string DownloadsLocation {
            get {
                return ResourceManager.GetString("DownloadsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New downloads location set.
        /// </summary>
        public static string DownloadsLocationSet {
            get {
                return ResourceManager.GetString("DownloadsLocationSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads pruning policy.
        /// </summary>
        public static string DownloadsPruningPolicy {
            get {
                return ResourceManager.GetString("DownloadsPruningPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string DownloadSuccess {
            get {
                return ResourceManager.GetString("DownloadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop APK to sideload, release folder to install or backup folder to restore.
        /// </summary>
        public static string DragDropPanelText {
            get {
                return ResourceManager.GetString("DragDropPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable auto donation.
        /// </summary>
        public static string EnableAutoDonation {
            get {
                return ResourceManager.GetString("EnableAutoDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically upload all eligible games.
        /// </summary>
        public static string EnableAutoDonationTooltip {
            get {
                return ResourceManager.GetString("EnableAutoDonationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable remote logging.
        /// </summary>
        public static string EnableRemoteLogging {
            get {
                return ResourceManager.GetString("EnableRemoteLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow automatic sending of logs.
        /// </summary>
        public static string EnableRemoteLoggingTooltip {
            get {
                return ResourceManager.GetString("EnableRemoteLoggingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Wireless ADB.
        /// </summary>
        public static string EnableWirelessAdb {
            get {
                return ResourceManager.GetString("EnableWirelessAdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding task.
        /// </summary>
        public static string ErrorAddingTask {
            get {
                return ResourceManager.GetString("ErrorAddingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting APK info.
        /// </summary>
        public static string ErrorApkInfo {
            get {
                return ResourceManager.GetString("ErrorApkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error applying device settings.
        /// </summary>
        public static string ErrorApplyingDeviceSettings {
            get {
                return ResourceManager.GetString("ErrorApplyingDeviceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error running auto donation.
        /// </summary>
        public static string ErrorAutoDonation {
            get {
                return ResourceManager.GetString("ErrorAutoDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while checking device connection.
        /// </summary>
        public static string ErrorCheckingDeviceConnection {
            get {
                return ResourceManager.GetString("ErrorCheckingDeviceConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking for updates.
        /// </summary>
        public static string ErrorCheckingForUpdates {
            get {
                return ResourceManager.GetString("ErrorCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while opening game details dialog.
        /// </summary>
        public static string ErrorGameDetailsDialog {
            get {
                return ResourceManager.GetString("ErrorGameDetailsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while notifying about device state change.
        /// </summary>
        public static string ErrorNotifyingDeviceStateChange {
            get {
                return ResourceManager.GetString("ErrorNotifyingDeviceStateChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error refreshing available games.
        /// </summary>
        public static string ErrorRefreshingAvailableGames {
            get {
                return ResourceManager.GetString("ErrorRefreshingAvailableGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error refreshing installed games.
        /// </summary>
        public static string ErrorRefreshingInstalledGames {
            get {
                return ResourceManager.GetString("ErrorRefreshingInstalledGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception has been copied to clipboard.
        /// </summary>
        public static string ExceptionCopiedToClipboard {
            get {
                return ResourceManager.GetString("ExceptionCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        public static string Extract {
            get {
                return ResourceManager.GetString("Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull selected apps from device.
        /// </summary>
        public static string ExtractAppsTooltip {
            get {
                return ResourceManager.GetString("ExtractAppsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction failed.
        /// </summary>
        public static string ExtractionFailed {
            get {
                return ResourceManager.GetString("ExtractionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Selected.
        /// </summary>
        public static string ExtractSelected {
            get {
                return ResourceManager.GetString("ExtractSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted.
        /// </summary>
        public static string ExtractSuccess {
            get {
                return ResourceManager.GetString("ExtractSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed: no device connection.
        /// </summary>
        public static string FailedNoDeviceConnection {
            get {
                return ResourceManager.GetString("FailedNoDeviceConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete downloaded files.
        /// </summary>
        public static string FailedToDeleteDownloadedFiles {
            get {
                return ResourceManager.GetString("FailedToDeleteDownloadedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enable Wireless ADB.
        /// </summary>
        public static string FailedToEnableWirelessAdb {
            get {
                return ResourceManager.GetString("FailedToEnableWirelessAdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize video player.
        /// </summary>
        public static string FailedToInitVideoPlayer {
            get {
                return ResourceManager.GetString("FailedToInitVideoPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load current device settings.
        /// </summary>
        public static string FailedToLoadDeviceSettings {
            get {
                return ResourceManager.GetString("FailedToLoadDeviceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load popularity data.
        /// </summary>
        public static string FailedToLoadPopularity {
            get {
                return ResourceManager.GetString("FailedToLoadPopularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reload mirror list.
        /// </summary>
        public static string FailedToReloadMirrorList {
            get {
                return ResourceManager.GetString("FailedToReloadMirrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save settings.
        /// </summary>
        public static string FailedToSaveSettings {
            get {
                return ResourceManager.GetString("FailedToSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start ADB server.
        /// </summary>
        public static string FailedToStartAdbServer {
            get {
                return ResourceManager.GetString("FailedToStartAdbServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to switch mirror.
        /// </summary>
        public static string FailedToSwitchMirror {
            get {
                return ResourceManager.GetString("FailedToSwitchMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force rescan.
        /// </summary>
        public static string ForceDevicesRescanButton {
            get {
                return ResourceManager.GetString("ForceDevicesRescanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Name.
        /// </summary>
        public static string GameNameHeader {
            get {
                return ResourceManager.GetString("GameNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Size.
        /// </summary>
        public static string GameSizeHeader {
            get {
                return ResourceManager.GetString("GameSizeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored.
        /// </summary>
        public static string Ignored {
            get {
                return ResourceManager.GetString("Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide selected apps from donation list (select already ignored apps to inverse).
        /// </summary>
        public static string IgnoreSelectedAppsTooltip {
            get {
                return ResourceManager.GetString("IgnoreSelectedAppsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Selected.
        /// </summary>
        public static string IgnoreSelectedButton {
            get {
                return ResourceManager.GetString("IgnoreSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible update, reinstalling.
        /// </summary>
        public static string IncompatibleUpdateReinstalling {
            get {
                return ResourceManager.GetString("IncompatibleUpdateReinstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation ID copied to clipboard.
        /// </summary>
        public static string InstallationIdCopied {
            get {
                return ResourceManager.GetString("InstallationIdCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Games.
        /// </summary>
        public static string InstalledGamesHeader {
            get {
                return ResourceManager.GetString("InstalledGamesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Version.
        /// </summary>
        public static string InstalledVersionHeader {
            get {
                return ResourceManager.GetString("InstalledVersionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install failed.
        /// </summary>
        public static string InstallFailed {
            get {
                return ResourceManager.GetString("InstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        public static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing APK.
        /// </summary>
        public static string InstallingApk {
            get {
                return ResourceManager.GetString("InstallingApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install queued.
        /// </summary>
        public static string InstallQueued {
            get {
                return ResourceManager.GetString("InstallQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string InstallSuccess {
            get {
                return ResourceManager.GetString("InstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install trailers addon.
        /// </summary>
        public static string InstallTrailersAddonButton {
            get {
                return ResourceManager.GetString("InstallTrailersAddonButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        public static string LastUpdatedHeader {
            get {
                return ResourceManager.GetString("LastUpdatedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Release Name.
        /// </summary>
        public static string LatestReleaseNameHeader {
            get {
                return ResourceManager.GetString("LatestReleaseNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        public static string Limit {
            get {
                return ResourceManager.GetString("Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link has been copied to clipboard.
        /// </summary>
        public static string LinkCopiedToClipboard {
            get {
                return ResourceManager.GetString("LinkCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loader Settings.
        /// </summary>
        public static string LoaderSettingsHeader {
            get {
                return ResourceManager.GetString("LoaderSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingEllipsis {
            get {
                return ResourceManager.GetString("LoadingEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected location is not writable.
        /// </summary>
        public static string LocationNotWritable {
            get {
                return ResourceManager.GetString("LocationNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info.
        /// </summary>
        public static string MoreInfoButton {
            get {
                return ResourceManager.GetString("MoreInfoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount Quest as Drive.
        /// </summary>
        public static string MountQuestButton {
            get {
                return ResourceManager.GetString("MountQuestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameHeader {
            get {
                return ResourceManager.GetString("NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New app.
        /// </summary>
        public static string NewApp {
            get {
                return ResourceManager.GetString("NewApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version.
        /// </summary>
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No apps selected.
        /// </summary>
        public static string NoAppsSelected {
            get {
                return ResourceManager.GetString("NoAppsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No apps to donate.
        /// </summary>
        public static string NoAppsToDonate {
            get {
                return ResourceManager.GetString("NoAppsToDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backups selected.
        /// </summary>
        public static string NoBackupsSelected {
            get {
                return ResourceManager.GetString("NoBackupsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device connection.
        /// </summary>
        public static string NoDeviceConnection {
            get {
                return ResourceManager.GetString("NoDeviceConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No games selected.
        /// </summary>
        public static string NoGamesSelected {
            get {
                return ResourceManager.GetString("NoGamesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No games to update.
        /// </summary>
        public static string NoGamesToUpdate {
            get {
                return ResourceManager.GetString("NoGamesToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No games to update ({0} skipped).
        /// </summary>
        public static string NoGamesToUpdateSkipped {
            get {
                return ResourceManager.GetString("NoGamesToUpdateSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mirrors available.
        /// </summary>
        public static string NoMirrorsAvailable {
            get {
                return ResourceManager.GetString("NoMirrorsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like the game, buy it to support the developers.
        /// </summary>
        public static string OculusStoreLinkTooltip {
            get {
                return ResourceManager.GetString("OculusStoreLinkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Device.
        /// </summary>
        public static string OnDeviceHeader {
            get {
                return ResourceManager.GetString("OnDeviceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Apps.
        /// </summary>
        public static string OtherAppsHeader {
            get {
                return ResourceManager.GetString("OtherAppsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing custom install.
        /// </summary>
        public static string PerformingCustomInstall {
            get {
                return ResourceManager.GetString("PerformingCustomInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity (1 day).
        /// </summary>
        public static string Popularity1DHeader {
            get {
                return ResourceManager.GetString("Popularity1DHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity (30 days).
        /// </summary>
        public static string Popularity30DHeader {
            get {
                return ResourceManager.GetString("Popularity30DHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity (7 days).
        /// </summary>
        public static string Popularity7DHeader {
            get {
                return ResourceManager.GetString("Popularity7DHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity time range.
        /// </summary>
        public static string PopularityTimeRange {
            get {
                return ResourceManager.GetString("PopularityTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred connection type.
        /// </summary>
        public static string PreferredConnectionType {
            get {
                return ResourceManager.GetString("PreferredConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to upload.
        /// </summary>
        public static string PreparingToUpload {
            get {
                return ResourceManager.GetString("PreparingToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulling from device.
        /// </summary>
        public static string PullingFromDevice {
            get {
                return ResourceManager.GetString("PullingFromDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing OBB files.
        /// </summary>
        public static string PushingObbFiles {
            get {
                return ResourceManager.GetString("PushingObbFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Settings.
        /// </summary>
        public static string QuestSettingsHeader {
            get {
                return ResourceManager.GetString("QuestSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redownload games list.
        /// </summary>
        public static string RefreshAvailableGamesTooltip {
            get {
                return ResourceManager.GetString("RefreshAvailableGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload list of backups.
        /// </summary>
        public static string RefreshBackupsTooltip {
            get {
                return ResourceManager.GetString("RefreshBackupsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshButton {
            get {
                return ResourceManager.GetString("RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan installed apps.
        /// </summary>
        public static string RefreshInstalledAppsTooltip {
            get {
                return ResourceManager.GetString("RefreshInstalledAppsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan installed games.
        /// </summary>
        public static string RefreshInstalledGamesTooltip {
            get {
                return ResourceManager.GetString("RefreshInstalledGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Name.
        /// </summary>
        public static string ReleaseNameHeader {
            get {
                return ResourceManager.GetString("ReleaseNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string ReloadButton {
            get {
                return ResourceManager.GetString("ReloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload list.
        /// </summary>
        public static string ReloadListButton {
            get {
                return ResourceManager.GetString("ReloadListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Backups.
        /// </summary>
        public static string RestoreBackupsHeader {
            get {
                return ResourceManager.GetString("RestoreBackupsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restored default settings.
        /// </summary>
        public static string RestoredDefaultSettings {
            get {
                return ResourceManager.GetString("RestoredDefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Defaults.
        /// </summary>
        public static string RestoreDefaultsButton {
            get {
                return ResourceManager.GetString("RestoreDefaultsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore failed.
        /// </summary>
        public static string RestoreFailed {
            get {
                return ResourceManager.GetString("RestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore queued.
        /// </summary>
        public static string RestoreQueued {
            get {
                return ResourceManager.GetString("RestoreQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore selected backups.
        /// </summary>
        public static string RestoreSelectedBackupsTooltip {
            get {
                return ResourceManager.GetString("RestoreSelectedBackupsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Selected.
        /// </summary>
        public static string RestoreSelectedButton {
            get {
                return ResourceManager.GetString("RestoreSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup restored.
        /// </summary>
        public static string RestoreSuccess {
            get {
                return ResourceManager.GetString("RestoreSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring backup.
        /// </summary>
        public static string RestoringBackup {
            get {
                return ResourceManager.GetString("RestoringBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select backups folder.
        /// </summary>
        public static string SelectBackupsFolder {
            get {
                return ResourceManager.GetString("SelectBackupsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination folder.
        /// </summary>
        public static string SelectDestinationFolder {
            get {
                return ResourceManager.GetString("SelectDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select downloads folder.
        /// </summary>
        public static string SelectDownloadsFolder {
            get {
                return ResourceManager.GetString("SelectDownloadsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected mirror.
        /// </summary>
        public static string SelectedMirror {
            get {
                return ResourceManager.GetString("SelectedMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string SetButton {
            get {
                return ResourceManager.GetString("SetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show debug console.
        /// </summary>
        public static string ShowDebugConsole {
            get {
                return ResourceManager.GetString("ShowDebugConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hidden.
        /// </summary>
        public static string ShowHidden {
            get {
                return ResourceManager.GetString("ShowHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusHeader {
            get {
                return ResourceManager.GetString("StatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store rating.
        /// </summary>
        public static string StoreRating {
            get {
                return ResourceManager.GetString("StoreRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task failed.
        /// </summary>
        public static string TaskFailed {
            get {
                return ResourceManager.GetString("TaskFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task {0} failed.
        /// </summary>
        public static string TaskNameFailed {
            get {
                return ResourceManager.GetString("TaskNameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string TasksHeader {
            get {
                return ResourceManager.GetString("TasksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will uninstall selected apps.
        ///Are you sure you want to continue?.
        /// </summary>
        public static string UninstallAppsConfirmation {
            get {
                return ResourceManager.GetString("UninstallAppsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, uninstall.
        /// </summary>
        public static string UninstallAppsConfirmationButton {
            get {
                return ResourceManager.GetString("UninstallAppsConfirmationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall selected apps.
        /// </summary>
        public static string UninstallAppsTooltip {
            get {
                return ResourceManager.GetString("UninstallAppsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall failed.
        /// </summary>
        public static string UninstallFailed {
            get {
                return ResourceManager.GetString("UninstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will attempt to backup data
        ///and uninstall selected games.
        ///Are you sure you want to continue?.
        /// </summary>
        public static string UninstallGamesConfirmation {
            get {
                return ResourceManager.GetString("UninstallGamesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, uninstall.
        /// </summary>
        public static string UninstallGamesConfirmationButton {
            get {
                return ResourceManager.GetString("UninstallGamesConfirmationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling.
        /// </summary>
        public static string Uninstalling {
            get {
                return ResourceManager.GetString("Uninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall queued.
        /// </summary>
        public static string UninstallQueued {
            get {
                return ResourceManager.GetString("UninstallQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Selected.
        /// </summary>
        public static string UninstallSelectedButton {
            get {
                return ResourceManager.GetString("UninstallSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup and uninstall selected games.
        /// </summary>
        public static string UninstallSelectedGamesTooltip {
            get {
                return ResourceManager.GetString("UninstallSelectedGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalled.
        /// </summary>
        public static string UninstallSuccess {
            get {
                return ResourceManager.GetString("UninstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update All.
        /// </summary>
        public static string UpdateAllButton {
            get {
                return ResourceManager.GetString("UpdateAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update all games (excluding ambiguous installs).
        /// </summary>
        public static string UpdateAllGamesTooltip {
            get {
                return ResourceManager.GetString("UpdateAllGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available! ({0} -&gt; {1}).
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Selected.
        /// </summary>
        public static string UpdateSelectedButton {
            get {
                return ResourceManager.GetString("UpdateSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update selected games.
        /// </summary>
        public static string UpdateSelectedGamesTooltip {
            get {
                return ResourceManager.GetString("UpdateSelectedGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Status.
        /// </summary>
        public static string UpdateStatusHeader {
            get {
                return ResourceManager.GetString("UpdateStatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        public static string UploadSuccess {
            get {
                return ResourceManager.GetString("UploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up To Date.
        /// </summary>
        public static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username (leave empty for default).
        /// </summary>
        public static string UsernamePlaceholder {
            get {
                return ResourceManager.GetString("UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Code.
        /// </summary>
        public static string VersionCodeHeader {
            get {
                return ResourceManager.GetString("VersionCodeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Name.
        /// </summary>
        public static string VersionNameHeader {
            get {
                return ResourceManager.GetString("VersionNameHeader", resourceCulture);
            }
        }
    }
}
